CREATE DATABASE SkillBridgeDb;
GO

USE SkillBridgeDb;
GO

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Name NVARCHAR(120) NOT NULL,
    Email NVARCHAR(180) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(128) NOT NULL,
    Role NVARCHAR(32) NOT NULL,
    AvatarUrl NVARCHAR(500) NOT NULL,
    Bio NVARCHAR(1000) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    IsLocked BIT NOT NULL DEFAULT 0
);

CREATE TABLE TeacherProfiles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Skill NVARCHAR(160) NOT NULL,
    Description NVARCHAR(1200) NOT NULL,
    PricePerSession DECIMAL(18,2) NOT NULL,
    TeachingMode NVARCHAR(32) NOT NULL,
    Rating DECIMAL(3,2) NOT NULL,
    IsOnline BIT NOT NULL,
    DefaultPayoutMethod NVARCHAR(80) NOT NULL DEFAULT N'Tài khoản ngân hàng',
    DefaultPayoutBank NVARCHAR(80) NOT NULL DEFAULT 'Vietcombank',
    CONSTRAINT FK_TeacherProfiles_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE StudentProfiles (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    DisplayName NVARCHAR(120) NOT NULL,
    Email NVARCHAR(180) NOT NULL,
    Gender NVARCHAR(40) NOT NULL DEFAULT '',
    DateOfBirth DATE NULL,
    Phone NVARCHAR(40) NOT NULL DEFAULT '',
    LearningGoal NVARCHAR(700) NOT NULL DEFAULT '',
    Bio NVARCHAR(1000) NOT NULL DEFAULT '',
    AvatarUrl NVARCHAR(500) NOT NULL DEFAULT '',
    UpdatedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT FK_StudentProfiles_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Bookings (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    StudentId UNIQUEIDENTIFIER NOT NULL,
    TeacherId UNIQUEIDENTIFIER NOT NULL,
    StartTime DATETIMEOFFSET NOT NULL,
    EndTime DATETIMEOFFSET NOT NULL,
    Status NVARCHAR(32) NOT NULL,
    MeetingRoomId NVARCHAR(120) NOT NULL,
    CONSTRAINT FK_Bookings_Students FOREIGN KEY (StudentId) REFERENCES Users(Id),
    CONSTRAINT FK_Bookings_Teachers FOREIGN KEY (TeacherId) REFERENCES Users(Id)
);

CREATE TABLE Messages (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    SenderId UNIQUEIDENTIFIER NOT NULL,
    ReceiverId UNIQUEIDENTIFIER NOT NULL,
    Content NVARCHAR(2000) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    IsRead BIT NOT NULL DEFAULT 0,
    CONSTRAINT FK_Messages_Senders FOREIGN KEY (SenderId) REFERENCES Users(Id),
    CONSTRAINT FK_Messages_Receivers FOREIGN KEY (ReceiverId) REFERENCES Users(Id)
);

CREATE TABLE Notifications (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Icon NVARCHAR(16) NOT NULL,
    Title NVARCHAR(220) NOT NULL,
    Body NVARCHAR(600) NOT NULL,
    IsRead BIT NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT FK_Notifications_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Transactions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BookingId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Type NVARCHAR(32) NOT NULL,
    Status NVARCHAR(32) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT FK_Transactions_Bookings FOREIGN KEY (BookingId) REFERENCES Bookings(Id)
);

CREATE TABLE TeacherReviews (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BookingId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    TeacherId UNIQUEIDENTIFIER NOT NULL,
    StudentId UNIQUEIDENTIFIER NOT NULL,
    Stars INT NOT NULL,
    Comment NVARCHAR(1000) NOT NULL DEFAULT '',
    CreatedAt DATETIMEOFFSET NOT NULL,
    CONSTRAINT FK_TeacherReviews_Bookings FOREIGN KEY (BookingId) REFERENCES Bookings(Id),
    CONSTRAINT FK_TeacherReviews_Teachers FOREIGN KEY (TeacherId) REFERENCES Users(Id),
    CONSTRAINT FK_TeacherReviews_Students FOREIGN KEY (StudentId) REFERENCES Users(Id)
);

CREATE TABLE PaymentInvoices (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    InvoiceCode NVARCHAR(40) NOT NULL,
    BookingId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    StudentId UNIQUEIDENTIFIER NOT NULL,
    TeacherId UNIQUEIDENTIFIER NOT NULL,
    LessonContent NVARCHAR(500) NOT NULL,
    TeachingMode NVARCHAR(32) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentMethod NVARCHAR(80) NOT NULL,
    Status NVARCHAR(32) NOT NULL,
    PaidAt DATETIMEOFFSET NOT NULL,
    UpdatedAt DATETIMEOFFSET NULL,
    CONSTRAINT FK_PaymentInvoices_Bookings FOREIGN KEY (BookingId) REFERENCES Bookings(Id)
);

CREATE TABLE WalletTransactions (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Type NVARCHAR(32) NOT NULL,
    Method NVARCHAR(80) NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(80) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    BookingId UNIQUEIDENTIFIER NULL,
    WithdrawalId UNIQUEIDENTIFIER NULL,
    Note NVARCHAR(500) NOT NULL DEFAULT '',
    TransactionCode NVARCHAR(40) NOT NULL DEFAULT '',
    CONSTRAINT FK_WalletTransactions_Users FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Complaints (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    BookingId UNIQUEIDENTIFIER NOT NULL UNIQUE,
    StudentId UNIQUEIDENTIFIER NOT NULL,
    TeacherId UNIQUEIDENTIFIER NOT NULL,
    Reason NVARCHAR(1000) NOT NULL,
    StudentEvidenceUrl NVARCHAR(700) NOT NULL DEFAULT '',
    TeacherResponse NVARCHAR(1200) NOT NULL DEFAULT '',
    TeacherEvidenceUrl NVARCHAR(700) NOT NULL DEFAULT '',
    Status NVARCHAR(40) NOT NULL,
    CreatedAt DATETIMEOFFSET NOT NULL,
    TeacherRespondedAt DATETIMEOFFSET NULL,
    ResolvedAt DATETIMEOFFSET NULL,
    CONSTRAINT FK_Complaints_Bookings FOREIGN KEY (BookingId) REFERENCES Bookings(Id),
    CONSTRAINT FK_Complaints_Students FOREIGN KEY (StudentId) REFERENCES Users(Id),
    CONSTRAINT FK_Complaints_Teachers FOREIGN KEY (TeacherId) REFERENCES Users(Id)
);
